name: balajiicode
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
#  speech_to_text_ultra: ^0.0.3
  lottie: ^3.1.3
  http:
  provider: ^6.1.2
  flutter_easyloading: ^3.0.5
  webview_flutter:
#  shared_preferences:

  #n
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.2
  flutter_mobx: ^2.2.1+1
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2
  image: ^4.3.0
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  country_code_picker: ^3.1.0
  telephony: ^0.2.0
  dropdown_search: ^6.0.1



  #Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_auth: ^5.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependencies_overrides:
  speech_to_text: ^7.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottiefile/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
