name: balajiicode
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  uuid: ^4.5.1
  speech_to_text: ^6.6.2
  flutter_tts: ^3.8.4
  speech_to_text_ultra: ^0.0.3
  lottie: ^3.1.2
  http:
  provider: ^6.0.1
  flutter_easyloading: ^3.0.5
  webview_flutter:
#  shared_preferences:

  #n
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  flutter_mobx: ^2.2.1+1
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.1
  image: ^4.2.0
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.0
  country_code_picker: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottiefile/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
