// Shared Pref

const IS_FIRST_TIME = 'IS_FIRST_TIME';
const IS_REMEMBER = 'IS_REMEMBER';
const FIRSTNAME = "FIRSTNAME";
const LASTNAME = "LASTNAME";
const USER_ID = "USER_ID";
const USER_NATIVE_LANGUAGE = "USER_NATIVE_LANGUAGE";
const USER_ENGLISH_PROFICIENCY= "USER_ENGLISH_PROFICIENCY";


const IS_LOGIN = "IS_LOGIN";
const TOKEN = "TOKEN";
const PHONE_NUMBER = "PHONE_NUMBER";

const FIREBASEAPIKEY = 'AIzaSyCY5DQ73GU_NMCjfdABkf_f172EJ_K5Y9s';
const FIREBASEAPPID = '1:349682106028:android:4527c36ba0244d5ee1e909';
const FIREBASEMESSAGINGSENDERID ='349682106028';
const FIREBASEPROJECTID ='zap-ai-1a07d';

const statusSuccess = 'User registered successfully';








