

import '../Screens/authentication/profile_details_screen.dart';

final List<Language> languages = [
  Language(englishName: 'Mandarin Chinese', nativeName: '中文'),
  Language(englishName: 'Spanish', nativeName: 'Español'),
  Language(englishName: 'English', nativeName: 'English'),
  Language(englishName: 'Hindi', nativeName: 'हिन्दी'),
  Language(englishName: 'Arabic', nativeName: 'العربية'),
  Language(englishName: 'Portuguese', nativeName: 'Português'),
  Language(englishName: 'Bengali', nativeName: 'বাংলা'),
  Language(englishName: 'Russian', nativeName: 'Русский'),
  Language(englishName: 'Japanese', nativeName: '日本語'),
  Language(englishName: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ'),
  Language(englishName: 'German', nativeName: 'Deutsch'),
  Language(englishName: 'Javanese', nativeName: 'Basa Jawa'),
  Language(englishName: 'Wu (Shanghainese)', nativeName: '吴语'),
  Language(englishName: 'Malay/Indonesian', nativeName: 'Bahasa Melayu / Bahasa Indonesia'),
  Language(englishName: 'Telugu', nativeName: 'తెలుగు'),
  Language(englishName: 'Vietnamese', nativeName: 'Tiếng Việt'),
  Language(englishName: 'Korean', nativeName: '한국어'),
  Language(englishName: 'French', nativeName: 'Français'),
  Language(englishName: 'Marathi', nativeName: 'मराठी'),
  Language(englishName: 'Tamil', nativeName: 'தமிழ்'),
  Language(englishName: 'Urdu', nativeName: 'اردو'),
  Language(englishName: 'Turkish', nativeName: 'Türkçe'),
  Language(englishName: 'Italian', nativeName: 'Italiano'),
  Language(englishName: 'Thai', nativeName: 'ไทย'),
  Language(englishName: 'Gujarati', nativeName: 'ગુજરાતી'),
  Language(englishName: 'Polish', nativeName: 'Polski'),
  Language(englishName: 'Ukrainian', nativeName: 'Українська'),
  Language(englishName: 'Persian (Farsi)', nativeName: 'فارسی'),
  Language(englishName: 'Romanian', nativeName: 'Română'),
  Language(englishName: 'Dutch', nativeName: 'Nederlands'),
  Language(englishName: 'Greek', nativeName: 'Ελληνικά'),
  Language(englishName: 'Hungarian', nativeName: 'Magyar'),
  Language(englishName: 'Czech', nativeName: 'Čeština'),
  Language(englishName: 'Swedish', nativeName: 'Svenska'),
  Language(englishName: 'Finnish', nativeName: 'Suomi'),
  Language(englishName: 'Hebrew', nativeName: 'עברית'),
  Language(englishName: 'Danish', nativeName: 'Dansk'),
  Language(englishName: 'Norwegian', nativeName: 'Norsk'),
  Language(englishName: 'Slovak', nativeName: 'Slovenčina'),
  Language(englishName: 'Bulgarian', nativeName: 'Български'),
  Language(englishName: 'Serbian', nativeName: 'Српски'),
  Language(englishName: 'Croatian', nativeName: 'Hrvatski'),
  Language(englishName: 'Malayalam', nativeName: 'മലയാളം'),
  Language(englishName: 'Kannada', nativeName: 'ಕನ್ನಡ'),
  Language(englishName: 'Odia', nativeName: 'ଓଡ଼ିଆ'),
  Language(englishName: 'Assamese', nativeName: 'অসমীয়া'),
  Language(englishName: 'Maithili', nativeName: 'मैथिली'),
  Language(englishName: 'Sindhi', nativeName: 'سنڌي'),
  Language(englishName: 'Nepali', nativeName: 'नेपाली'),
  Language(englishName: 'Pashto', nativeName: 'پښتو'),
  Language(englishName: 'Amharic', nativeName: 'አማርኛ'),
  Language(englishName: 'Yoruba', nativeName: 'Yorùbá'),
  Language(englishName: 'Igbo', nativeName: 'Asụsụ Igbo'),
  Language(englishName: 'Zulu', nativeName: 'isiZulu'),
  Language(englishName: 'Swahili', nativeName: 'Kiswahili'),
  Language(englishName: 'Hausa', nativeName: 'Hausa'),
  Language(englishName: 'Burmese', nativeName: 'မြန်မာစာ'),
  Language(englishName: 'Khmer', nativeName: 'ភាសាខ្មែរ'),
  Language(englishName: 'Lao', nativeName: 'ພາສາລາວ'),
  Language(englishName: 'Sinhala', nativeName: 'සිංහල'),
  Language(englishName: 'Mongolian', nativeName: 'Монгол хэл'),
  Language(englishName: 'Tibetan', nativeName: 'བོད་ཡིག'),
  Language(englishName: 'Kazakh', nativeName: 'Қазақ тілі'),
  Language(englishName: 'Uzbek', nativeName: 'Oʻzbek tili'),
  Language(englishName: 'Azerbaijani', nativeName: 'Azərbaycan dili'),
  Language(englishName: 'Georgian', nativeName: 'ქართული'),
  Language(englishName: 'Armenian', nativeName: 'Հայերեն'),
  Language(englishName: 'Albanian', nativeName: 'Shqip'),
  Language(englishName: 'Bosnian', nativeName: 'Bosanski'),
  Language(englishName: 'Macedonian', nativeName: 'Македонски'),
  Language(englishName: 'Slovenian', nativeName: 'Slovenščina'),
  Language(englishName: 'Estonian', nativeName: 'Eesti'),
  Language(englishName: 'Latvian', nativeName: 'Latviešu'),
  Language(englishName: 'Lithuanian', nativeName: 'Lietuvių'),
  Language(englishName: 'Icelandic', nativeName: 'Íslenska'),
  Language(englishName: 'Irish', nativeName: 'Gaeilge'),
  Language(englishName: 'Welsh', nativeName: 'Cymraeg'),
  Language(englishName: 'Basque', nativeName: 'Euskara'),
  Language(englishName: 'Catalan', nativeName: 'Català'),
  Language(englishName: 'Galician', nativeName: 'Galego'),
  Language(englishName: 'Esperanto', nativeName: 'Esperanto'),
  Language(englishName: 'Haitian Creole', nativeName: 'Kreyòl Ayisyen'),
  Language(englishName: 'Tagalog', nativeName: 'Wikang Tagalog'),
  Language(englishName: 'Filipino', nativeName: 'Wikang Filipino'),
  Language(englishName: 'Sundanese', nativeName: 'Basa Sunda'),
  Language(englishName: 'Balochi', nativeName: 'بلوچی'),
  Language(englishName: 'Kurdish', nativeName: 'Kurdî'),
  Language(englishName: 'Tigrinya', nativeName: 'ትግርኛ'),
  Language(englishName: 'Somali', nativeName: 'Af-Soomaali'),
  Language(englishName: 'Quechua', nativeName: 'Runa Simi'),
  Language(englishName: 'Aymara', nativeName: 'Aymar aru'),
  Language(englishName: 'Guarani', nativeName: 'Avañe\'ẽ'),
  Language(englishName: 'Fijian', nativeName: 'Na Vosa Vakaviti'),
  Language(englishName: 'Samoan', nativeName: 'Gagana Sāmoa'),
  Language(englishName: 'Tongan', nativeName: 'Faka Tonga'),
  Language(englishName: 'Maori', nativeName: 'Te Reo Māori'),
  Language(englishName: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi'),
  Language(englishName: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ'),
  Language(englishName: 'Greenlandic', nativeName: 'Kalaallisut'),
  Language(englishName: 'Luxembourgish', nativeName: 'Lëtzebuergesch'),
  Language(englishName: 'Maltese', nativeName: 'Malti'),
  Language(englishName: 'Belarusian', nativeName: 'Беларуская'),
  Language(englishName: 'Macedonian', nativeName: 'Македонски'),
  Language(englishName: 'Tajik', nativeName: 'Тоҷикӣ'),
  Language(englishName: 'Turkmen', nativeName: 'Türkmençe'),
  Language(englishName: 'Chuvash', nativeName: 'Чӑваш чӗлхи'),
  Language(englishName: 'Chechen', nativeName: 'Нохчийн мотт'),
  Language(englishName: 'Uighur', nativeName: 'ئۇيغۇرچە'),
  Language(englishName: 'Dzongkha', nativeName: 'རྫོང་ཁ'),
  Language(englishName: 'Sanskrit', nativeName: 'संस्कृतम्'),
  Language(englishName: 'Tatar', nativeName: 'Татарча'),
  Language(englishName: 'Māori', nativeName: 'Te Reo Māori'),
  Language(englishName: 'Faroese', nativeName: 'Føroyskt'),
  Language(englishName: 'Sardinian', nativeName: 'Sardu'),
  Language(englishName: 'Corsican', nativeName: 'Corsu'),
  Language(englishName: 'Frisian', nativeName: 'Frysk'),
  Language(englishName: 'Breton', nativeName: 'Brezhoneg'),
  Language(englishName: 'Occitan', nativeName: 'Occitan'),
  Language(englishName: 'Ladino', nativeName: 'Djudeo-Espanyol'),
  Language(englishName: 'Yiddish', nativeName: 'ייִדיש'),
  Language(englishName: 'Romani', nativeName: 'Romani'),
  Language(englishName: 'Nahuatl', nativeName: 'Nāhuatl'),
  Language(englishName: 'Ojibwe', nativeName: 'Anishinaabemowin'),
  Language(englishName: 'Cherokee', nativeName: 'ᏣᎳᎩ'),
  Language(englishName: 'Hmong', nativeName: 'Hmoob'),
  Language(englishName: 'Zulu', nativeName: 'isiZulu'),
  Language(englishName: 'Xhosa', nativeName: 'isiXhosa'),
  Language(englishName: 'Sesotho', nativeName: 'Sesotho'),
  Language(englishName: 'Tswana', nativeName: 'Setswana'),
  Language(englishName: 'Afrikaans', nativeName: 'Afrikaans'),
  Language(englishName: 'Shona', nativeName: 'ChiShona'),
  Language(englishName: 'Kinyarwanda', nativeName: 'Ikinyarwanda'),
  Language(englishName: 'Kirundi', nativeName: 'Ikirundi'),
  Language(englishName: 'Lingala', nativeName: 'Lingála'),
  Language(englishName: 'Twi', nativeName: 'Twi'),
  Language(englishName: 'Fulah', nativeName: 'Pulaar'),
  Language(englishName: 'Wolof', nativeName: 'Wollof'),
  Language(englishName: 'Berber', nativeName: 'ⵜⴰⵎⴰⵣⵉⵖⵜ'),
];
final List<String> englishLevelList = [
  'Beginner',
  'Intermediate',
  'Advanced',
];
String selectedLanguage = 'Hindi';
String englishLevel = 'Beginner';